name: Live Screen Capture

on:
  workflow_dispatch:

  schedule:
    # 5:00 PM IST = 11:30 AM UTC
    - cron: "30 11 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread mysql-connector-python selenium webdriver-manager

      - name: Run Script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          GSPREAD_CREDENTIALS: ${{ secrets.GSPREAD_CREDENTIALS }}
          TRADINGVIEW_COOKIES: ${{ secrets.TRADINGVIEW_COOKIES }}
        run: python live.py
